version: '2'

services:
  NetSoc-DNS01:
    image: tomcraftmc/bind9-dns:latest
    restart: always
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - /docker/storage/dns/named.conf:/etc/bind/named.conf
      - /docker/storage/dns/truesdale.ovh:/etc/bind/master/truesdale.ovh
