version: '2'

services:
  investor_wp:
    image: wordpress
    restart: unless-stopped
    depends_on:
      - investor_mysql
    environment:
      WORDPRESS_DB_HOST: investor_mysql
      WORDPRESS_DB_USER: NetSocAdmin
      WORDPRESS_DB_PASSWORD: P*2RI8Va4o)qsz!So7
      WORDPRESS_DB_NAME: wordpress
      VIRTUAL_HOST: investor.netsoc.dit.ie
      LETSENCRYPT_HOST: investor.netsoc.dit.ie
      LETSENCRYPT_EMAIL: netsoc@socs.dit.ie
    volumes:
     - ./code:/code
     - ./html:/var/www/html

  investor_mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: NetSocAdmin
      MYSQL_PASSWORD: P*2RI8Va4o)qsz!So7
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /db:/var/lib/mysql

networks:
  default:
    external:
      name: nginx-proxy
