version: "3"
services:
  wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=a1QboQKIE15GAYvXwXHE
     - VIRTUAL_HOST = enactus.netsoc.dit.ie
    restart: always
    volumes:
     - ./code:/code
     - ./html:/var/www/html
  mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=a1QboQKIE15GAYvXwXHE
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql
networks:
  default:
    external:
      name: nginx-proxy
