version: '2'

services:
  enactus_wp:
    image: wordpress
    restart: unless-stopped
    depends_on:
      - enactus_mysql
    environment:
      WORDPRESS_DB_HOST: enactus_mysql
      WORDPRESS_DB_USER: NetSocAdmin
      WORDPRESS_DB_PASSWORD: P*2RI8Va4o)qsz!So7
      WORDPRESS_DB_NAME: wordpress
      VIRTUAL_HOST: enactus.netsoc.dit.ie
      LETSENCRYPT_HOST: enactus.netsoc.dit.ie
      LETSENCRYPT_EMAIL: netsoc@socs.dit.ie
    volumes:
     - /docker/storage/Enactus/code:/code
     - /docker/storage/Enactus/html:/var/www/html/wp-content
     -./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  enactus_mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: NetSocAdmin
      MYSQL_PASSWORD: P*2RI8Va4o)qsz!So7
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /docker/storage/Enactus/db:/var/lib/mysql

networks:
  default:
    external:
      name: nginx-proxy
