version: '2.3'
services:
    FreeIPAServer:
        image: freeipa/freeipa-server
        restart: always
        hostname: ipa
        domainname: netsoc.dit.ie
        privileged: true
        volumes:
            - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
            - '/docker/storage/freeipa:/data:Z'
        ports:
            - '8097:80'
            - '9444:443'
            - '389:389'
            - '636:636'
            - '88:88'
            - '464:464'
            - '88:88/udp'
            - '464:464/udp'
            - '123:123/udp'
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
        networks:
            - traefik-public
        labels:
        - traefik.frontend.rule=Host:ipa.netsoc.dit.ie
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
networks:
  traefik-public:
    external: true
