version: '3'
services:
  letsencrypt-nginx-proxy-companion:
    volumes:
      - /docker/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    image: jrcs/letsencrypt-nginx-proxy-companion

networks:
  default:
    external:
      name: nginx-proxy
