version: '2'

services:
  NetSoc-DNS01:
    image: tomcraftmc/bind9-dns:latest
    restart: always
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - /docker/storage/dns/named.conf:/etc/bind/named.conf
      - /docker/storage/dns/netsoc.dit.ie:/etc/bind/master/netsoc.dit.ie
