version: '2'

services:
  netsoc_web:
    image: httpd
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: bics.netsoc.dit.ie
      LETSENCRYPT_HOST: netsoc.dit.ie
      LETSENCRYPT_EMAIL: netsoc@socs.dit.ie
    volumes:
     - /docker/storage/NetSoc.dit.ie/Comp-Web/public:/usr/local/apache2/htdocs/

networks:
  default:
    external:
      name: nginx-proxy
