version: '3.3'

services:
  ouroboros:
    image: pyouroboros/ouroboros
    environment:
      - SWARM=true
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE=mongo influxdb postgres mariadb
      - TZ=America/Chicago
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        - com.ouroboros.enable=true
    networks:
      - default
